/** Stable machine-readable response codes returned by the API. */
export enum RESPONSE_MESSAGE {
  INTERNAL_ERROR = "INTERNAL_ERROR",
  HEALTH_CHECK_SUCCESS = "HEALTH_CHECK_SUCCESS",
  VALIDATION_FAILED = "VALIDATION_FAILED",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",

  OTP_SEND_SUCCESS = "OTP_SEND_SUCCESS",
  OTP_SEND_FAILED = "OTP_SEND_FAILED",
  OTP_RESEND_SUCCESS = "OTP_RESEND_SUCCESS",
  OTP_RESEND_FAILED = "OTP_RESEND_FAILED",
  OTP_RESEND_COOLDOWN_ACTIVE = "OTP_RESEND_COOLDOWN_ACTIVE",
  OTP_INVALID = "OTP_INVALID",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_VERIFICATION_SUCCESS = "OTP_VERIFICATION_SUCCESS",
  OTP_VERIFICATION_FAILED = "OTP_VERIFICATION_FAILED",

  AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS",
  AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",

  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_NOT_FOUND = "USER_NOT_FOUND",

  EVENT_CREATED = "EVENT_CREATED",
  EVENT_UPDATED = "EVENT_UPDATED",
  EVENT_DELETED = "EVENT_DELETED",
  EVENT_NOT_FOUND = "EVENT_NOT_FOUND",
}
