export const PERMISSION = {
  EVENT_READ: "EVENT:READ",
  EVENT_LIST: "EVENT:LIST",
  EVENT_CREATE: "EVENT:CREATE",
  EVENT_UPDATE: "EVENT:UPDATE",
  EVENT_DELETE: "EVENT:DELETE",
  EVENT_PUBLISH: "EVENT:PUBLISH",
} as const;

export type IPermission = (typeof PERMISSION)[keyof typeof PERMISSION];
